/**
 * src/db/seed.js
 * =============================================================================
 * Seeds ALL users into the database from the Excel hierarchy sheet.
 *
 * Run:  node src/db/seed.js
 *
 * LOGIN CREDENTIALS:
 *   Regular employees / RM / HOD  → their Gmail from Excel | FirstName@123
 *   Department HODs               → dept@rts.com           | Dept@123
 *                                   e.g. software@rts.com  | Software@123
 *   Admin                         → admin@rts.com          | Admin@123
 *
 * Safe to run multiple times — existing users are skipped (not duplicated).
 * =============================================================================
 */

"use strict";

require("dotenv").config();
const { PrismaClient } = require("@prisma/client");
const bcrypt           = require("bcryptjs");

const prisma = new PrismaClient();

// =============================================================================
// USER LIST — derived from Dept_wise_hirarchy_Details.xlsx
// Role logic:
//   HOD     = appeared in HOD column for other employees
//   RM      = appeared in Reporting Manager column (not already HOD)
//   Employee = everyone else
// =============================================================================
const USERS = [
  // ── EMPLOYEES, RMs, HODs (from Excel) ─────────────────────────────────────
  { empId:"A-1001",   name:"Prasanna Gajanana Hegde",          email:"prasannahegdetarimane@gmail.com",   role:"RM",       dept:"Accounts",                 designation:"Director",                             location:"Bangalore", password:"Prasanna@123"    },
  { empId:"A-1007",   name:"Santhosh S M",                     email:"santhosh.sm9@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Facilitator-analyst and notes",         location:"Bangalore", password:"Santhosh@123"    },
  { empId:"A-1127",   name:"Anil Kumar G",                     email:"kadakkath@gmail.com",               role:"RM",       dept:"Academic",                 designation:"Team Lead",                             location:"Bangalore", password:"Anil@123"        },
  { empId:"A-1148",   name:"BIKASH Hazarika",                  email:"bik.haz.1989@gmail.com",            role:"RM",       dept:"Operation",                designation:"Regional Manager",                      location:"Guwahati",  password:"Bikash@123"      },
  { empId:"AC-1030",  name:"Nithish V",                        email:"v.nithish@gmail.com",               role:"HOD",      dept:"Software",                 designation:"Software Developer",                    location:"Bangalore", password:"Nithish@123"     },
  { empId:"AC-1053",  name:"Rinkoomani Kotoki",                email:"rinkoomanikotoki@gmail.com",         role:"RM",       dept:"Academic",                 designation:"Senior Academic Expert - Science",       location:"Guwahati",  password:"Rinkoomani@123"  },
  { empId:"AC-1056",  name:"Dhrubajeet Kalita",                email:"dhrubajeetkalita4@gmail.com",        role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Guwahati",  password:"Dhrubajeet@123"  },
  { empId:"AC-1063",  name:"Parvez Alom Choudhury",            email:"parvezalomchoudhury@gmail.com",      role:"RM",       dept:"Operation",                designation:"Regional Manager",                      location:"Cachar",    password:"Parvez@123"      },
  { empId:"AC-1064",  name:"Mrinmay Boro",                     email:"mrinmayboro777@gmail.com",           role:"Requestor", dept:"Broadcasting",             designation:"Network engineer",                      location:"Kokrajhar", password:"Mrinmay@123"     },
  { empId:"AC-1067",  name:"Deep Jyoti Sarma",                 email:"deepjsharma@yahoo.com",              role:"RM",       dept:"Operation",                designation:"Project Manager",                       location:"Nagaland",  password:"Deep@123"        },
  { empId:"AC-1069",  name:"Sindhu Shrikant Hegde",            email:"sindhuhegde743118@gmail.com",        role:"Requestor", dept:"Management",               designation:"Asst Executive - Management",           location:"Bangalore", password:"Sindhu@123"      },
  { empId:"AC-1073",  name:"Anuja Bora",                       email:"boraanuja2@gmail.com",               role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Guwahati",  password:"Anuja@123"       },
  { empId:"AC-1074",  name:"Manoranjan Kalita",                email:"monukalita785623@gmail.com",          role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Dhemaji",   password:"Manoranjan@123"  },
  { empId:"AC-1075",  name:"Chinmay Deka",                     email:"cdeka7748@gmail.com",                role:"Requestor", dept:"Technical Support",        designation:"Technical Support Executive",           location:"Guwahati",  password:"Chinmay@123"     },
  { empId:"AC-1099",  name:"Karthika K Nair",                  email:"kknair2998@gmail.com",               role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Bangalore", password:"Karthika@123"    },
  { empId:"AC-1103",  name:"Nishant Bhat",                     email:"nishantb2022@gmail.com",             role:"RM",       dept:"Business Development",     designation:"Executive Vice President",              location:"Bangalore", password:"Nishant@123"     },
  { empId:"AC-1105",  name:"Kalyan Jyoti Boro",                email:"kalyan.boro11@gmail.com",            role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Kokrajhar", password:"Kalyan@123"      },
  { empId:"AC-1112",  name:"Gandoli Basumatary",               email:"gandolibasumatary123@gmail.com",     role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Kokrajhar", password:"Gandoli@123"     },
  { empId:"AC-1114",  name:"Arun K G",                         email:"arunabhatkg@gmail.com",              role:"Requestor", dept:"Admin",                    designation:"Executive",                             location:"Bangalore", password:"Arun@123"        },
  { empId:"AC-1120",  name:"Maneesh Mallikarjun Lakajanavar",  email:"maneeshlakaji@gmail.com",            role:"Requestor", dept:"Animation",                designation:"3D Animator",                           location:"Hubli",     password:"Maneesh@123"     },
  { empId:"AC-1121",  name:"RAMANAGOUDA V PATIL",              email:"ramanagoudapatil1996@gmail.com",     role:"Requestor", dept:"Animation",                designation:"3D Animator",                           location:"Hubli",     password:"Ramanagouda@123" },
  { empId:"AC-1122",  name:"Tyagaraj M Badiger",               email:"tyagaraj22@gmail.com",               role:"Requestor", dept:"Animation",                designation:"3D Artist",                             location:"Hubli",     password:"Tyagaraj@123"    },
  { empId:"AC-1123",  name:"Venkataraman Santosh Achari",      email:"shashankachari52@gmail.com",         role:"Requestor", dept:"Animation",                designation:"3D Animator",                           location:"Hubli",     password:"Venkataraman@123"},
  { empId:"AC-1130",  name:"Kungur Hazorika",                  email:"kungurhazorika@gmail.com",           role:"RM",       dept:"Academic",                 designation:"Team Lead",                             location:"Kokrajhar", password:"Kungur@123"      },
  { empId:"AC-1131",  name:"Rakesh Talukdar",                  email:"rakeyshtalukdar198@gmail.com",       role:"Requestor", dept:"Accounts",                 designation:"Accounts Executive",                    location:"Guwahati",  password:"Rakesh@123"      },
  { empId:"AC-1133",  name:"Pavan T V",                        email:"pavantallam03@gmail.com",            role:"HOD",      dept:"Accounts",                 designation:"Finance Manager",                       location:"Bangalore", password:"Pavan@123"       },
  { empId:"AC-1138",  name:"Sandeep Kumar Verma",              email:"sandeepkumarjsd@gmail.com",          role:"Requestor", dept:"Store",                    designation:"Store executive",                       location:"Guwahati",  password:"Sandeep@123"     },
  { empId:"AC-1139",  name:"Rahul Subba",                      email:"rhlsubba19@gmail.com",               role:"RM",       dept:"Technical Support",        designation:"Team Lead",                             location:"Guwahati",  password:"Rahul@123"       },
  { empId:"AC-1142",  name:"Rinku Pran Thakuria",              email:"rinkuthakuria13@gmail.com",          role:"RM",       dept:"Operation",                designation:"Regional Manager",                      location:"Guwahati",  password:"Rinku@123"       },
  { empId:"AC-1145",  name:"CHANDANA DAS",                     email:"cdas7452@gmail.com",                 role:"Requestor", dept:"Documantation",            designation:"Executive",                             location:"Guwahati",  password:"Chandana@123"    },
  { empId:"AC-1156",  name:"MANTU BARMAN",                     email:"mantubarman52@gmail.com",            role:"Requestor", dept:"Technical Support",        designation:"Technical Support Executive",           location:"Guwahati",  password:"Mantu@123"       },
  { empId:"AC-1161",  name:"Nilakhee Kalita",                  email:"nilakheekalita19@gmail.com",         role:"Requestor", dept:"Academic",                 designation:"Subject matter expert - Geography",     location:"Guwahati",  password:"Nilakhee@123"    },
  { empId:"AC-1165",  name:"Bruno Lyngdoh Boro",               email:"brunoboro9@gmail.com",               role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Diphu",     password:"Bruno@123"       },
  { empId:"AC-1168",  name:"Navasmita Das",                    email:"navasmitadas.11@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - English",       location:"Guwahati",  password:"Navasmita@123"   },
  { empId:"AC-1171",  name:"PRANJIT DAS",                      email:"pranjitdas@rts.com",                 role:"Requestor", dept:"Store",                    designation:"Assistant",                             location:"Guwahati",  password:"Pranjit@123"     },
  { empId:"AC-1172",  name:"Dharamveer KUMAR",                 email:"dharamveer61015@gmail.com",          role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Dehradun",  password:"Dharamveer@123"  },
  { empId:"AC-1175",  name:"Anusuya Chakraborty",              email:"anusuyachak9@gmail.com",             role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Guwahati",  password:"Anusuya@123"     },
  { empId:"AC-1177",  name:"BISWANATH DAS",                    email:"biswanath.panna.das@gmail.com",      role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Biswanath@123"   },
  { empId:"AC-1178",  name:"OLI CHOUDHURY",                    email:"olichoudhary658@gmail.com",          role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Oli@123"         },
  { empId:"AC-1179",  name:"Sourav Pradhan",                   email:"souravpradhan130@gmail.com",         role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Sourav@123"      },
  { empId:"AC-1181",  name:"Arpita Gopal Bhat",                email:"bhat.arpita23@gmail.com",            role:"Requestor", dept:"Accounts",                 designation:"Accounts Executive",                    location:"Bangalore", password:"Arpita@123"      },
  { empId:"AC-1182",  name:"CHANDAMITA MISHRA",                email:"mishrachandamita629@gmail.com",      role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Computer",      location:"Guwahati",  password:"Chandamita@123"  },
  { empId:"AC-1184",  name:"SOURAV DEY",                       email:"souravpost49@gmail.com",             role:"Requestor", dept:"System admin",             designation:"System Administrator",                  location:"Guwahati",  password:"Sourav@123"      },
  { empId:"AC-1191",  name:"Ravikant Sharma",                  email:"ravikant.sharma64@yahoo.com",        role:"RM",       dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Dehradun",  password:"Ravikant@123"    },
  { empId:"AC-1193",  name:"Siroswrang Goyary",                email:"goyaryswrang@gmail.com",             role:"Requestor", dept:"Academic",                 designation:"Subject matter expert - Geography",     location:"Kokrajhar", password:"Siroswrang@123"  },
  { empId:"AC-1194",  name:"ASHOK KUMAR SINGHA",               email:"ashoklongjam@hotmail.com",           role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Silchar",   password:"Ashok@123"       },
  { empId:"AC-1201",  name:"BIRDAW Boro",                      email:"birdawboro321@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Kokrajhar", password:"Birdaw@123"      },
  { empId:"AC-1203",  name:"Mithlesh Guleria",                 email:"mithlesh_guleria@rediffmail.com",    role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Dehradun",  password:"Mithlesh@123"    },
  { empId:"AC-1206",  name:"PRAKASH MAJHI",                    email:"prakashmajhi2412@gmail.com",         role:"Requestor", dept:"Academic",                 designation:"Data Entry Operator",                   location:"Guwahati",  password:"Prakash@123"     },
  { empId:"AC-1207",  name:"Supriya Bangaru",                  email:"supriyabangaru8@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Bangalore", password:"Supriya@123"     },
  { empId:"AC-1208",  name:"POOJA BHARTI",                     email:"poojabharti4m@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Sr. Subject Matter Expert - Physics",   location:"Bangalore", password:"Pooja@123"       },
  { empId:"AC-1209",  name:"Phwrdan Khakhlari",                email:"phwrdankhakhlari03@gmail.com",       role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Phwrdan@123"     },
  { empId:"AC-1210",  name:"Divya H M",                        email:"divyahmmahadev1998@gmail.com",       role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Divya@123"       },
  { empId:"AC-1216",  name:"Jwngsar Owary",                    email:"jwngsarowary3@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Data Entry Operator",                   location:"Kokrajhar", password:"Jwngsar@123"     },
  { empId:"AC-1219",  name:"KUKIL NATH",                       email:"nathkukil4@gmail.com",               role:"Requestor", dept:"Store",                    designation:"Assistant",                             location:"Guwahati",  password:"Kukil@123"       },
  { empId:"AC-1220",  name:"Kavya Seetaram Hegde",             email:"hegdekavya123@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Bangalore", password:"Kavya@123"       },
  { empId:"AC-1222",  name:"Naveenkumar Sidramappa Itagi",     email:"naveenkumaritagi54321@gmail.com",    role:"Requestor", dept:"Animation",                designation:"3D Animator",                           location:"Hubli",     password:"Naveenkumar@123" },
  { empId:"AC-1225",  name:"LALIT SINHA",                      email:"lalitsinha86@gmail.com",             role:"Requestor", dept:"System admin",             designation:"System Administrator",                  location:"Silchar",   password:"Lalit@123"       },
  { empId:"AC-1228",  name:"Asha Narasimha Hegde",             email:"ashahegde17@gmail.com",              role:"Requestor", dept:"HR",                       designation:"Sr. Recruitment Consultant",            location:"Bangalore", password:"Asha@123"        },
  { empId:"AC-1229",  name:"Mousam Gupta",                     email:"mousamgupta@rts.com",                role:"Requestor", dept:"Academic",                 designation:"Data Entry Operator",                   location:"Silchar",   password:"Mousam@123"      },
  { empId:"AC-1231",  name:"Vishal Bhimrao Kharat",            email:"vkharat9594@gmail.com",              role:"Requestor", dept:"Animation",                designation:"3D Artist",                             location:"Bangalore", password:"Vishal@123"      },
  { empId:"AC-1232",  name:"Abhishek Govind Nayak",            email:"abhisheknayak263@gmail.com",         role:"Requestor", dept:"System admin",             designation:"System Administrator",                  location:"Bangalore", password:"Abhishek@123"    },
  { empId:"AC-1239",  name:"Mridusmita Das",                   email:"mridusmitadas9594@gmail.com",        role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Guwahati",  password:"Mridusmita@123"  },
  { empId:"AC-1240",  name:"RAHUL PEGU",                       email:"pegurahul2017@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Guwahati",  password:"Rahul@123"       },
  { empId:"AC-1245",  name:"Aparajita Acharjee",               email:"appi.manu87@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Silchar",   password:"Aparajita@123"   },
  { empId:"AC-1246",  name:"Monidipa Nath Choudhury",          email:"monidipa.nathchoudhury@gmail.com",   role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Silchar",   password:"Monidipa@123"    },
  { empId:"AC-1248",  name:"Shrinidhi Irodi",                  email:"shrinidhi.irodi@gmail.com",          role:"HOD",      dept:"Software",                 designation:"Data Engineer",                         location:"Bangalore", password:"Shrinidhi@123"   },
  { empId:"AC-1249",  name:"Roseline Mathew Ramapuram",        email:"roselinemathewr@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Bangalore", password:"Roseline@123"    },
  { empId:"AC-1250",  name:"Pooja Poovamma N.P",               email:"poojapoovamma77@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Bangalore", password:"Pooja@123"       },
  { empId:"AC-1251",  name:"KRISHNA PRASAD",                   email:"krishnaprasadp63@gmail.com",         role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Bangalore", password:"Krishna@123"     },
  { empId:"AC-1252",  name:"Diptarka Gohain",                  email:"diptarka.5@gmail.com",               role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - English",       location:"Guwahati",  password:"Diptarka@123"    },
  { empId:"AC-1253",  name:"KALYAN CH BARMA",                  email:"kalyanbarma33@gmail.com",            role:"Requestor", dept:"Technical Support",        designation:"Technical Support Executive",           location:"Guwahati",  password:"Kalyan@123"      },
  { empId:"AC-1256",  name:"SOURAV JYOTI TALUKDAR",            email:"souravjyotitalukdar048@gmail.com",   role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Guwahati",  password:"Sourav@123"      },
  { empId:"AC-1257",  name:"Vipin Prasad Dangwal",             email:"vipin303030@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Dehradun",  password:"Vipin@123"       },
  { empId:"AC-1258",  name:"Sujeet Kumar",                     email:"sujeetkumargaya47@gmail.com",        role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Dehradun",  password:"Sujeet@123"      },
  { empId:"AC-1262",  name:"Animesh Shee",                     email:"animaxshee98@gmail.com",             role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Silchar",   password:"Animesh@123"     },
  { empId:"AC-1264",  name:"Aruna M",                          email:"aadyaanjan@gmail.com",               role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Bangalore", password:"Aruna@123"       },
  { empId:"AC-1265",  name:"Sharada Hegde",                    email:"sharadahegde91@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Sharada@123"     },
  { empId:"AC-1266",  name:"Durga Sarma",                      email:"psarma530@gmail.com",                role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Durga@123"       },
  { empId:"AC-1267",  name:"Suchitra Vinayak Hegde",           email:"shuchihegde@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Bangalore", password:"Suchitra@123"    },
  { empId:"AC-1269",  name:"Vishal Rajeshyam Shirahatti",      email:"vishalshirahatti2005@gmail.com",     role:"Requestor", dept:"Animation",                designation:"3D Animator",                           location:"Hubli",     password:"Vishal@123"      },
  { empId:"AC-1270",  name:"NAVEEN VAGELE SURESH",             email:"naveenvagele@gmail.com",             role:"Requestor", dept:"Animation",                designation:"3D Modelling",                          location:"Bangalore", password:"Naveen@123"      },
  { empId:"AC-1271",  name:"Nidhi Nautiyal",                   email:"nidhinauty450@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Dehradun",  password:"Nidhi@123"       },
  { empId:"AC-1273",  name:"Rupa Devi Choudhury",              email:"rupadchoudhury@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Sr. Subject Matter Expert - Biology",   location:"Guwahati",  password:"Rupa@123"        },
  { empId:"AC-1275",  name:"Reena Borah",                      email:"reenaborah6@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Sr.Subject Matter Expert - Mathematics",location:"Guwahati",  password:"Reena@123"       },
  { empId:"AC-1279",  name:"Priyabrata Sinha",                 email:"priyabratasinha7@gmail.com",         role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Silchar",   password:"Priyabrata@123"  },
  { empId:"AC-1280",  name:"Debdulal Sharma",                  email:"debdulalsharma@gmail.com",           role:"RM",       dept:"Academic",                 designation:"Team Lead - Silchar",                   location:"Silchar",   password:"Debdulal@123"    },
  { empId:"AC-1287",  name:"Antony Allan",                     email:"antonyallan2002@gmail.com",          role:"Requestor", dept:"Animation",                designation:"Trainee",                               location:"Bangalore", password:"Antony@123"      },
  { empId:"AC-1289",  name:"Darshan K Naik",                   email:"darshanaknaik3652@gmail.com",        role:"Requestor", dept:"Animation",                designation:"3D Animator",                           location:"Bangalore", password:"Darshan@123"     },
  { empId:"AC-1290",  name:"Sridevi G R",                      email:"srismartkids14@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Sr. Subject Matter Expert - FLN",       location:"Bangalore", password:"Sridevi@123"     },
  { empId:"AC-1291",  name:"B V Nitin",                        email:"bvnitinbhandari94099@gmail.com",     role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Bangalore", password:"B@123"           },
  { empId:"AC-1294",  name:"Geeta D Gownalli",                 email:"geetagownalli22@gmail.com",          role:"Requestor", dept:"Software",                 designation:"Software Developer",                    location:"Bangalore", password:"Geeta@123"       },
  { empId:"AC-1295",  name:"Rohith Gowda",                     email:"rohitrohitgowda57@gmail.com",        role:"Requestor", dept:"Animation",                designation:"3D Animator",                           location:"Bangalore", password:"Rohith@123"      },
  { empId:"AC-1296",  name:"Tanurima Dasgupta",                email:"tanurima720@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - English",       location:"Silchar",   password:"Tanurima@123"    },
  { empId:"AC-1297",  name:"DOLI ROY",                         email:"roydoly804@gmail.com",               role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Doli@123"        },
  { empId:"AC-1305",  name:"Radhika K",                        email:"krishna.radhika958@gmail.com",       role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Radhika@123"     },
  { empId:"AC-1306",  name:"Anusha devi Anusha",               email:"anushamayur1990@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Anusha@123"      },
  { empId:"AC-1308",  name:"Rinki Kalita",                     email:"rinkikalita1998@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Guwahati",  password:"Rinki@123"       },
  { empId:"AC-1310",  name:"Shayan Rao S L",                   email:"generao@gmail.com",                  role:"RM",       dept:"Academic",                 designation:"Sr.Subject Matter Expert - Chemistry",  location:"Bangalore", password:"Shayan@123"      },
  { empId:"AC-1313",  name:"Parash Pallab Hazarika",           email:"parash161@gmail.com",                role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Guwahati",  password:"Parash@123"      },
  { empId:"AC-1314",  name:"Anush Gama",                       email:"anushsgr74@gmail.com",               role:"Requestor", dept:"Animation",                designation:"3D Artist",                             location:"Bangalore", password:"Anush@123"       },
  { empId:"AC-1315",  name:"Mabin T Domanic",                  email:"mebinikka@gmail.com",                role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Mabin@123"       },
  { empId:"AC-1316",  name:"Deepa Mattre",                     email:"digwaldipa@gmail.com",               role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Deepa@123"       },
  { empId:"AC-1318",  name:"Sanjay Bhat",                      email:"sabha1905@gmail.com",                role:"Requestor", dept:"Academic",                 designation:"Manager L&D- Academic",                 location:"Bangalore", password:"Sanjay@123"      },
  { empId:"AC-1319",  name:"Harini Sankaran",                  email:"harinisankar1116@gmail.com",         role:"Requestor", dept:"Corporate Communications", designation:"Content Writer",                        location:"Bangalore", password:"Harini@123"      },
  { empId:"AC-1322",  name:"Pritam Boro",                      email:"pritamboro42@gmail.com",             role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Guwahati",  password:"Pritam@123"      },
  { empId:"AC-1323",  name:"Tonemoi Narzary",                  email:"ntonemoi@gmail.com",                 role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - English",       location:"Kokrajhar", password:"Tonemoi@123"     },
  { empId:"AC-1325",  name:"Ganesh Terang",                    email:"g.ter4ng@gmail.com",                 role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Computer",      location:"Diphu",     password:"Ganesh@123"      },
  { empId:"AC-1328",  name:"Megha Bhatta",                     email:"meghabhatta13@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Guwahati",  password:"Megha@123"       },
  { empId:"AC-1333",  name:"Akshay Mahabaleshwar Bhat",        email:"akshaybhat1205@gmail.com",           role:"Requestor", dept:"Software",                 designation:"Associate Cloud Data Engineer",         location:"Bangalore", password:"Akshay@123"      },
  { empId:"AC-1336",  name:"Shreenidhi B",                     email:"shreenidhib50@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Bangalore", password:"Shreenidhi@123"  },
  { empId:"AC-1339",  name:"Athriba Mongzar",                  email:"a3bamongzar@gmail.com",              role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Nagaland",  password:"Athriba@123"     },
  { empId:"AC-1342",  name:"Sinchana C M",                     email:"sinchusss10@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Sr.Subject Matter Expert - Chemistry",  location:"Bangalore", password:"Sinchana@123"    },
  { empId:"AC-1344",  name:"Talari Shashi Kumar",              email:"shashianil001@gmail.com",            role:"Requestor", dept:"Software",                 designation:"Game Developer",                        location:"Bangalore", password:"Talari@123"      },
  { empId:"AC-1345",  name:"H R Manoj Kumar",                  email:"manojhurudi@gmail.com",              role:"Requestor", dept:"Software",                 designation:"Game Designer",                         location:"Bangalore", password:"H@123"           },
  { empId:"AC-1347",  name:"Vishwa Moger",                     email:"vishwamoger3@gmail.com",             role:"Requestor", dept:"Software",                 designation:"Game Developer",                        location:"Bangalore", password:"Vishwa@123"      },
  { empId:"AC-1348",  name:"Rakshitha Bangera",                email:"rakshithabangera16@gmail.com",       role:"Requestor", dept:"Software",                 designation:"Game Developer",                        location:"Bangalore", password:"Rakshitha@123"   },
  { empId:"AC-1350",  name:"Pramita Roy",                      email:"pramita900@gmail.com",               role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Guwahati",  password:"Pramita@123"     },
  { empId:"AC-1351",  name:"Abinav Raghunath",                 email:"abinavr1998@gmail.com",              role:"Requestor", dept:"Software",                 designation:"Game Designer",                         location:"Bangalore", password:"Abinav@123"      },
  { empId:"AC-1352",  name:"Manoj Mushahary",                  email:"manaj.mochahary1234@gmail.com",      role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Kokrajhar", password:"Manoj@123"       },
  { empId:"AC-1354",  name:"Shreya S",                         email:"shreyashetty1625@gmail.com",         role:"Requestor", dept:"Academic",                 designation:"Sr. Subject Matter Expert - Biology",   location:"Bangalore", password:"Shreya@123"      },
  { empId:"AC-1356",  name:"Javed Akhtar",                     email:"javedakhtar647473@gmail.com",        role:"Requestor", dept:"Technical Support",        designation:"Technical Support Executive",           location:"Guwahati",  password:"Javed@123"       },
  { empId:"AC-1357",  name:"Dimpy Choudhury",                  email:"munuchoudhary811@gmail.com",         role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Dimpy@123"       },
  { empId:"AC-1359",  name:"ANAMIKA BANIA",                    email:"anamikabania74@gmail.com",           role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Anamika@123"     },
  { empId:"AC-1360",  name:"Bhabesh Barman",                   email:"bbhabesh3@gmail.com",                role:"Requestor", dept:"Technical Support",        designation:"Technical Support Executive",           location:"Guwahati",  password:"Bhabesh@123"     },
  { empId:"AC-1365",  name:"RANTU PHUKAN",                     email:"rantuphukan342@gmail.com",           role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Rantu@123"       },
  { empId:"AC-1366",  name:"Dev Kumar Pradhan",                email:"devpradhan2316@gmail.com",           role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Dev@123"         },
  { empId:"AC-1371",  name:"Mohit Sharma",                     email:"mohitsharma09101999@gmail.com",      role:"Requestor", dept:"Software",                 designation:"Flutter Developer",                     location:"Bangalore", password:"Mohit@123"       },
  { empId:"AC-1373",  name:"Yeswanth P V",                     email:"yeswanthsajeev@gmail.com",           role:"Requestor", dept:"Animation",                designation:"3D Animator",                           location:"Hubli",     password:"Yeswanth@123"    },
  { empId:"AC-1375",  name:"Milton Marandi",                   email:"marandimilton@gmail.com",            role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Dhemaji",   password:"Milton@123"      },
  { empId:"AC-1376",  name:"Siva Karthikayan",                 email:"sivakarthikayan.cs@gmail.com",       role:"Requestor", dept:"Software",                 designation:"Flutter Developer",                     location:"Bangalore", password:"Siva@123"        },
  { empId:"AC-1378",  name:"Pavan Verma",                      email:"pvnverma77@gmail.com",               role:"RM",       dept:"Purchase",                 designation:"Procurement Manager",                   location:"Dehradun",  password:"Pavan@123"       },
  { empId:"AC-1379",  name:"Vamsi Krishna Agnihotram",         email:"vkagnihotram@gmail.com",             role:"HOD",      dept:"Operation",                designation:"Sr.Project Manager",                    location:"Bangalore", password:"Vamsi@123"       },
  { empId:"AC-1380",  name:"Pankaj Kumar",                     email:"pk004086@gmail.com",                 role:"Requestor", dept:"Operation",                designation:"TL-Technical Support",                  location:"Dehradun",  password:"Pankaj@123"      },
  { empId:"AC-1381",  name:"Raveendra Ganapati Bhat",          email:"bhatraveendrabeegar@gmail.com",      role:"HOD",      dept:"Academic",                 designation:"Academic head-Education and Training",  location:"Bangalore", password:"Raveendra@123"   },
  { empId:"AC-1384",  name:"Vishal Singh",                     email:"akash41195@gmail.com",               role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Bangalore", password:"Vishal@123"      },
  { empId:"AC-1385",  name:"Harjit Kour",                      email:"kourharjit12@gmail.com",             role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Guwahati",  password:"Harjit@123"      },
  { empId:"AC-1387",  name:"Manasee Devi",                     email:"manasee.ds@gmail.com",               role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Guwahati",  password:"Manasee@123"     },
  { empId:"AC-1388",  name:"Monika Nath",                      email:"monikanath111@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Silchar",   password:"Monika@123"      },
  { empId:"AC-1390",  name:"Lakhima Goyary",                   email:"lakhimagoyary@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Kokrajhar", password:"Lakhima@123"     },
  { empId:"AC-1391",  name:"Neil Kapuria",                     email:"neilkapuria@gmail.com",              role:"Requestor", dept:"Software",                 designation:"3D Artist",                             location:"Bangalore", password:"Neil@123"        },
  { empId:"AC-1392",  name:"Leo Leo",                          email:"leoallahu786@gmail.com",             role:"Requestor", dept:"Software",                 designation:"Digital Artist",                        location:"Bangalore", password:"Leo@123"         },
  { empId:"AC-1393",  name:"Rahul Bisht",                      email:"rahul3112singhbisht@gmail.com",      role:"Requestor", dept:"Operation",                designation:"Team Lead-Operations",                  location:"Dehradun",  password:"Rahul@123"       },
  { empId:"AC-1394",  name:"Vivek Kundaliya",                  email:"cplvivek@gmail.com",                 role:"Requestor", dept:"Operation",                designation:"Project coordinator",                   location:"Dehradun",  password:"Vivek@123"       },
  { empId:"AC-1395",  name:"Ashish Singh",                     email:"ashu8255781@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Dehradun",  password:"Ashish@123"      },
  { empId:"AC-1396",  name:"Amit Kumar",                       email:"kmr.amit0013@gmail.com",             role:"Requestor", dept:"Operation",                designation:"Store executive",                       location:"Dehradun",  password:"Amit@123"        },
  { empId:"AC-1397",  name:"Shivani Rajwar",                   email:"shivanirajwar2@gmail.com",           role:"Requestor", dept:"Operation",                designation:"Project coordinator",                   location:"Dehradun",  password:"Shivani@123"     },
  { empId:"AC-1398",  name:"Birkwswrang Basumatary",           email:"birkwswrang2000@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Educator",                              location:"Kokrajhar", password:"Birkwswrang@123" },
  { empId:"AC-1400",  name:"Anjani Basumatary",                email:"basumataryanjani01@gmail.com",       role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Kokrajhar", password:"Anjani@123"      },
  { empId:"AC-1401",  name:"Megha Hegde",                      email:"meghahegde980@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Coordinator",                           location:"Bangalore", password:"Megha@123"       },
  { empId:"AC-1402",  name:"Priyank Singh Bali",               email:"singhbalipriyank@gmail.com",         role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Dehradun",  password:"Priyank@123"     },
  { empId:"AC-1403",  name:"Chandan Kumar Sony",               email:"kumarsonychandan07@gmail.com",       role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Dehradun",  password:"Chandan@123"     },
  { empId:"AC-1404",  name:"Preeti Sagar Sagar",               email:"p16july@gmail.com",                  role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Dehradun",  password:"Preeti@123"      },
  { empId:"AC-1405",  name:"Abhishek Kumar",                   email:"abhishekkumar1391998@gmail.com",     role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Dehradun",  password:"Abhishek@123"    },
  { empId:"AC-1406",  name:"Karshika Boruah",                  email:"karshika996@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - English",       location:"Guwahati",  password:"Karshika@123"    },
  { empId:"AC-1408",  name:"Muskan Manchanda",                 email:"muskanmanchanda28@gmail.com",        role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Dehradun",  password:"Muskan@123"      },
  { empId:"AC-1409",  name:"Vidhi Sharma",                     email:"vidhi2000sharma@gmail.com",          role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Dehradun",  password:"Vidhi@123"       },
  { empId:"AC-1410",  name:"Pradeep Kumar",                    email:"kumarpradeep19998909@gmail.com",     role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Dehradun",  password:"Pradeep@123"     },
  { empId:"AC-1411",  name:"Anil Singh Panwar",                email:"anilsinghpanwar8107@gmail.com",      role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Dehradun",  password:"Anil@123"        },
  { empId:"AC-1413",  name:"Ayush Semwal",                     email:"ayushsemwal002@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Dehradun",  password:"Ayush@123"       },
  { empId:"AC-1414",  name:"Deekshitha S",                     email:"deekshitas01@gmail.com",             role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Bangalore", password:"Deekshitha@123"  },
  { empId:"AC-1415",  name:"Navin Singh",                      email:"singhnavinrangar3@gmail.com",        role:"Requestor", dept:"Operation",                designation:"Office Executive",                      location:"Dehradun",  password:"Navin@123"       },
  { empId:"AC-1417",  name:"Pragati Rawat",                    email:"rawatpragati25@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Dehradun",  password:"Pragati@123"     },
  { empId:"AC-1420",  name:"Manjunath S Bhagwath",             email:"padakamala327@gmail.com",            role:"Requestor", dept:"Purchase",                 designation:"Technical Material Management",         location:"Bangalore", password:"Manjunath@123"   },
  { empId:"AC-1422",  name:"Shubha Laxminarayan Hegde",        email:"hegdeshubha22@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Bangalore", password:"Shubha@123"      },
  { empId:"AC-1424",  name:"Ganga Datt Pant",                  email:"pantganga@gmail.com",                role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Dehradun",  password:"Ganga@123"       },
  { empId:"AC-1426",  name:"Apoorva G Bhat",                   email:"gbhatapoorva2@gmail.com",            role:"Requestor", dept:"Software",                 designation:"Data Analyst",                          location:"Bangalore", password:"Apoorva@123"     },
  { empId:"AC-1428",  name:"Arun Rawat",                       email:"arun.rawat1950@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"DTP",                                   location:"Dehradun",  password:"Arun@123"        },
  { empId:"AC-1429",  name:"Aishwarya M R",                    email:"aishumr2001@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Bangalore", password:"Aishwarya@123"   },
  { empId:"AC-1433",  name:"Neeraj Panwar",                    email:"neerajpanwar98@gmail.com",           role:"Requestor", dept:"System admin",             designation:"System Admin",                          location:"Dehradun",  password:"Neeraj@123"      },
  { empId:"AC-1434",  name:"Megha Mohan",                      email:"mmegha26@gmail.com",                 role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - English",       location:"Dehradun",  password:"Megha@123"       },
  { empId:"AC-1435",  name:"Hrishabh Jardhari",                email:"hrofficialtech@gmail.com",           role:"Requestor", dept:"Operation",                designation:"Team Lead",                             location:"Dehradun",  password:"Hrishabh@123"    },
  { empId:"AC-1436",  name:"Roshan Naik",                      email:"roshannaik4643@gmail.com",           role:"Requestor", dept:"Broadcasting",             designation:"Video Editor",                          location:"Bangalore", password:"Roshan@123"      },
  { empId:"AC-1437",  name:"Shivashree",                       email:"shivashree253@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Bangalore", password:"Shivashree@123"  },
  { empId:"AC-1439",  name:"Supriya Paul",                     email:"supriyopaul066@gmail.com",           role:"Requestor", dept:"Animation",                designation:"3D Artist",                             location:"Bangalore", password:"Supriya@123"     },
  { empId:"AC-1441",  name:"Megha A",                          email:"meghaa878909@gmail.com",             role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Bangalore", password:"Megha@123"       },
  { empId:"AC-1445",  name:"Nayana G",                         email:"nayana19398@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Sr.Subject Matter Expert - Chemistry",  location:"Bangalore", password:"Nayana@123"      },
  { empId:"AC-1447",  name:"Kannan Raveendran",                email:"kannan1997005@gmail.com",            role:"Requestor", dept:"Software",                 designation:"Digital Artist",                        location:"Bangalore", password:"Kannan@123"      },
  { empId:"AC-1448",  name:"Chinmay M",                        email:"chinmayisaiasst@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Bangalore", password:"Chinmay@123"     },
  { empId:"AC-1449",  name:"MAMATHA Y S",                      email:"mamathaprem05@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Bangalore", password:"Mamatha@123"     },
  { empId:"AC-1450",  name:"Pavitra Harihara Hegde",           email:"pavitrahegde60@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Bangalore", password:"Pavitra@123"     },
  { empId:"AC-1452",  name:"Sagar Singh Pimoli",               email:"sagarpimoli123@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Dehradun",  password:"Sagar@123"       },
  { empId:"AC-1454",  name:"Bhaskar Jyoti Baruah",             email:"piks17@gmail.com",                   role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Guwahati",  password:"Bhaskar@123"     },
  { empId:"AC-1455",  name:"Divya Rebecca D",                  email:"divyarebecca2002@gmail.com",         role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Bangalore", password:"Divya@123"       },
  { empId:"AC-1456",  name:"Rakesh Singh Negi",                email:"rakeshsinghnegi71@gmail.com",        role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Dehradun",  password:"Rakesh@123"      },
  { empId:"AC-1457",  name:"Srita G S",                        email:"sritagsathyan1@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Sr.Subject Matter Expert - Mathematics",location:"Bangalore", password:"Srita@123"       },
  { empId:"AC-1458",  name:"Swati Tomar",                      email:"swatikhalier100@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Dehradun",  password:"Swati@123"       },
  { empId:"AC-1459",  name:"Vidyasagar Bhat",                  email:"vidyasagarbhat106@gmail.com",        role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Bangalore", password:"Vidyasagar@123"  },
  { empId:"AC-1460",  name:"TRUPTHI M",                        email:"thrupthikulal0@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Bangalore", password:"Trupthi@123"     },
  { empId:"AC-1462",  name:"Neelkamal Joshi",                  email:"neeljoshi56@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Political Science",location:"Dehradun",password:"Neelkamal@123"   },
  { empId:"AC-1463",  name:"Greeshma R",                       email:"greeshma28012000@gmail.com",         role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Bangalore", password:"Greeshma@123"    },
  { empId:"AC-1464",  name:"Rohit Dattusa Miskin",             email:"rohitmiskin2001@gmail.com",          role:"Requestor", dept:"System admin",             designation:"System Admin",                          location:"Hubli",     password:"Rohit@123"       },
  { empId:"AC-1465",  name:"Sree Vidya S.",                    email:"vidhya.daiwik@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Sree@123"        },
  { empId:"AC-1467",  name:"Ankit Badoni",                     email:"ankit.badoni12@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Dehradun",  password:"Ankit@123"       },
  { empId:"AC-1468",  name:"Atul Badhani",                     email:"atulbadhani7@gmail.com",             role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Economics",     location:"Dehradun",  password:"Atul@123"        },
  { empId:"AC-1470",  name:"Krishna Kaffle",                   email:"krishnakaffle@gmail.com",            role:"Requestor", dept:"Broadcasting",             designation:"Video Editor",                          location:"Guwahati",  password:"Krishna@123"     },
  { empId:"AC-1471",  name:"Vimi Goyari",                      email:"vimigoyari425@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - English",       location:"Kokrajhar", password:"Vimi@123"        },
  { empId:"AC-1472",  name:"Vikas Prabhuling Gudarad",         email:"vikasgudarad9916@gmail.com",         role:"Requestor", dept:"Animation",                designation:"3D Artist",                             location:"Hubli",     password:"Vikas@123"       },
  { empId:"AC-1474",  name:"Emmanuel Bency",                   email:"emmanuel.physchool@gmail.com",       role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Bangalore", password:"Emmanuel@123"    },
  { empId:"AC-1475",  name:"Suma Hegde",                       email:"hv.sumahegde@gmail.com",             role:"Requestor", dept:"Software",                 designation:"Data Analyst",                          location:"Bangalore", password:"Suma@123"        },
  { empId:"AC-1478",  name:"Padmavathi N",                     email:"padmavathi29feb@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Padmavathi@123"  },
  { empId:"AC-1479",  name:"Manish Mathpal",                   email:"manishmathpal40@gmail.com",          role:"Requestor", dept:"Operation",                designation:"Technical Support Executive",           location:"Dehradun",  password:"Manish@123"      },
  { empId:"AC-1480",  name:"Upasana Basumatary",               email:"upasanabasumatary13@gmail.com",      role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Kokrajhar", password:"Upasana@123"     },
  { empId:"AC-1481",  name:"Akaash Madhu",                     email:"akaashprimad@gmail.com",             role:"Requestor", dept:"Animation",                designation:"3D Artist",                             location:"Bangalore", password:"Akaash@123"      },
  { empId:"AC-1483",  name:"Saurabh Kumar",                    email:"saurabhkumar4040@gmail.com",         role:"Requestor", dept:"Software",                 designation:"Software Developer",                    location:"Bangalore", password:"Saurabh@123"     },
  { empId:"AC-1484",  name:"Pavan Mahindrakar",                email:"pavanmahindrakar7@gmail.com",        role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Pavan@123"       },
  { empId:"AC-1485",  name:"Prashanthi Reddy",                 email:"prashanthi.muli@gmail.com",          role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Prashanthi@123"  },
  { empId:"AC-1487",  name:"SUPRITHA P",                       email:"suprithap2020@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Bangalore", password:"Supritha@123"    },
  { empId:"AC-1488",  name:"Ruchira Das Choudhury",            email:"ruchiradaschoudhury@gmail.com",      role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Guwahati",  password:"Ruchira@123"     },
  { empId:"AC-1489",  name:"Shourya Snehal",                   email:"shouryasnehal.2003@gmail.com",       role:"Requestor", dept:"Animation",                designation:"3D Artist",                             location:"Bangalore", password:"Shourya@123"     },
  { empId:"AC-1492",  name:"Preethi Jayachandra",              email:"preethijayachandra@gmail.com",       role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Preethi@123"     },
  { empId:"AC-1493",  name:"S Manoj Kumar",                    email:"manojkumaraka77@gmail.com",          role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"S@123"           },
  { empId:"AC-1494",  name:"Bhupal Singh Danu",                email:"danu.bhupal@gmail.com",              role:"Requestor", dept:"Operation",                designation:"Sr. Tech Exe",                          location:"Chamoli",   password:"Bhupal@123"      },
  { empId:"AC-1495",  name:"Vimal",                            email:"daparv365@gmail.com",                role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Dehradun",  password:"Vimal@123"       },
  { empId:"AC-1498",  name:"Madhushree U",                     email:"madhushreeu48@gmail.com",            role:"Requestor", dept:"Accounts",                 designation:"Accounts Executive",                    location:"Bangalore", password:"Madhushree@123"  },
  { empId:"AC-1499",  name:"Piju Daimary",                     email:"pijudaimary123@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Educator",                              location:"Kokrajhar", password:"Piju@123"        },
  { empId:"AC-1500",  name:"Khanij Jyoti Das",                 email:"khanij.jyotid@gmail.com",            role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Khanij@123"      },
  { empId:"AC-1501",  name:"Sourav Laskar",                    email:"laskar_sourav@rediffmail.com",       role:"Requestor", dept:"Operation",                designation:"Regional Manager",                      location:"Silchar",   password:"Sourav@123"      },
  { empId:"AC-1502",  name:"Chinmoy Talukdar",                 email:"chinmoyt052@gmail.com",              role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Chinmoy@123"     },
  { empId:"AC-1503",  name:"Naman Deep Joshi",                 email:"namandeepjoshi@gmail.com",           role:"Requestor", dept:"Operation",                designation:"Office Executive",                      location:"Dehradun",  password:"Naman@123"       },
  { empId:"AC-1505",  name:"Varshini S",                       email:"varshinibhat22@gmail.com",           role:"Requestor", dept:"Accounts",                 designation:"Finance Associate",                     location:"Bangalore", password:"Varshini@123"    },
  { empId:"AC-1506",  name:"Bharat Singh Panwar",              email:"bharataug1989@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject matter expert - Geography",     location:"Dehradun",  password:"Bharat@123"      },
  { empId:"AC-1507",  name:"Aman Raj Sharma",                  email:"amanr6812@gmail.com",                role:"Requestor", dept:"Animation",                designation:"FX Artist",                             location:"Bangalore", password:"Aman@123"        },
  { empId:"AC-1508",  name:"L Antony Silvester",               email:"l.antonysonu990@gmail.com",          role:"Requestor", dept:"Animation",                designation:"Motion Graphic Artist",                 location:"Bangalore", password:"L@123"           },
  { empId:"AC-1509",  name:"Dhruba Jyoti Bhuyan",              email:"dkjyotibhuyan@gmail.com",            role:"Requestor", dept:"Operation",                designation:"Regional Manager",                      location:"Dhemaji",   password:"Dhruba@123"      },
  { empId:"AC-1510",  name:"Gopika P G",                       email:"gopikag801@gmail.com",               role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Bangalore", password:"Gopika@123"      },
  { empId:"AC-1512",  name:"Manoj H A",                        email:"manojha346@gmail.com",               role:"Requestor", dept:"Software",                 designation:"Software Developer",                    location:"Bangalore", password:"Manoj@123"       },
  { empId:"AC-1513",  name:"Gayatri Kumari",                   email:"gayatri252920@gmail.com",            role:"Requestor", dept:"Accounts",                 designation:"Finance Associate",                     location:"Bangalore", password:"Gayatri@123"     },
  { empId:"AC-1514",  name:"Nayana S Joshi",                   email:"nayanasjoshi5@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Nayana@123"      },
  { empId:"AC-1515",  name:"Vartika Bisht",                    email:"vartikabisht13@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - English",       location:"Dehradun",  password:"Vartika@123"     },
  { empId:"AC-1517",  name:"Deepti Rakesh Joshi",              email:"joshideepti226@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Deepti@123"      },
  { empId:"AC-1518",  name:"Sweety Paul Das",                  email:"sweetydas2030@gmail.com",            role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Sweety@123"      },
  { empId:"AC-1519",  name:"Bhoomika R",                       email:"bhoomikar0233@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Bangalore", password:"Bhoomika@123"    },
  { empId:"AC-1520",  name:"Varsha N",                         email:"varshammu2003@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Varsha@123"      },
  { empId:"AC-1521",  name:"Usha S",                           email:"ushaparajji@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Usha@123"        },
  { empId:"AC-1522",  name:"Spoorthi JS",                      email:"spoorthijsvasishta2003@gmail.com",   role:"Requestor", dept:"Software",                 designation:"AI Developer",                          location:"Bangalore", password:"Spoorthi@123"    },
  { empId:"AC-1523",  name:"Y Ratan Kumar Singha",             email:"ratansingha77@gmail.com",            role:"Requestor", dept:"Broadcasting",             designation:"Quality Executive",                     location:"Silchar",   password:"Y@123"           },
  { empId:"AC-1524",  name:"Nandan Hegde",                     email:"nanduhegde505@gmail.com",            role:"Requestor", dept:"HR",                       designation:"Jr.Executive",                          location:"Bangalore", password:"Nandan@123"      },
  { empId:"AC-1525",  name:"Subham Deb",                       email:"subhamdeb247@gmail.com",             role:"Requestor", dept:"Operation",                designation:"Office Executive",                      location:"Silchar",   password:"Subham@123"      },
  { empId:"AC-1526",  name:"Sudeepta Kashyap",                 email:"kashyapsudeepta2@gmail.com",         role:"Requestor", dept:"Broadcasting",             designation:"Network engineer",                      location:"Guwahati",  password:"Sudeepta@123"    },
  { empId:"AC-1527",  name:"Debarshee Bora",                   email:"debu0771@gmail.com",                 role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Guwahati",  password:"Debarshee@123"   },
  { empId:"AC-1528",  name:"Neketta Namboori",                 email:"namboori456@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Sr.Subject Matter Expert - English",    location:"Dehradun",  password:"Neketta@123"     },
  { empId:"AC-1529",  name:"M P Vanishree",                    email:"mpvanishree@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Bangalore", password:"M@123"           },
  { empId:"AC-1530",  name:"RAJIB HALOI",                      email:"rajibhaloi26@yahoo.com",             role:"Requestor", dept:"Operation",                designation:"Regional Manager",                      location:"Guwahati",  password:"Rajib@123"       },
  { empId:"AC-1531",  name:"GAURAB JYOTI SARMA",               email:"gaurabjsarma987@gmail.com",          role:"Requestor", dept:"Operation",                designation:"Operation Executive",                   location:"Guwahati",  password:"Gaurab@123"      },
  { empId:"AC-1533",  name:"Madhusudan Nautiyal",              email:"madhusudannautiyal50@gmail.com",     role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Dehradun",  password:"Madhusudan@123"  },
  { empId:"AC-1534",  name:"Meghana P",                        email:"meghanaphudeth@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Chemistry",     location:"Bangalore", password:"Meghana@123"     },
  { empId:"AC-1535",  name:"Hirak Jyoti Pathak",               email:"pathakhirakjyoti@gmail.com",         role:"Requestor", dept:"Operation",                designation:"Regional Manager",                      location:"Kokrajhar", password:"Hirak@123"       },
  { empId:"AC-1536",  name:"Bineet Dey",                       email:"bineetdey18@gmail.com",              role:"Requestor", dept:"Accounts",                 designation:"Accounts Executive",                    location:"Guwahati",  password:"Bineet@123"      },
  { empId:"AC-1537",  name:"Anvayakrishna K",                  email:"anvaya27k@gmail.com",                role:"Requestor", dept:"Operation",                designation:"Asst. Manager Operations",              location:"Bangalore", password:"Anvayakrishna@123"},
  { empId:"AC-1538",  name:"Chaitrika U Hegde",                email:"chaiumeshhegde019@gmail.com",        role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Bangalore", password:"Chaitrika@123"   },
  { empId:"AC-1539",  name:"Bhoomika S",                       email:"bhoomikasuji@gmail.com",             role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Bangalore", password:"Bhoomika@123"    },
  { empId:"AC-1540",  name:"Triveni M",                        email:"triveni3d123@gmail.com",             role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - FLN",           location:"Bangalore", password:"Triveni@123"     },
  { empId:"AC-1542",  name:"Nayana A V",                       email:"nayanaav2002@gmail.com",             role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Physics",       location:"Bangalore", password:"Nayana@123"      },
  { empId:"AC-1543",  name:"Rashmi S",                         email:"rashmisrinivas871@gmail.com",        role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Bangalore", password:"Rashmi@123"      },
  { empId:"AI-393",   name:"Karabi Changmai",                  email:"karabichangmai8@gmail.com",           role:"Requestor", dept:"Operation",                designation:"Trainee",                               location:"Guwahati",  password:"Karabi@123"      },
  { empId:"C-1112",   name:"DEEPA SANDEEP KULKARNI",           email:"deepa.adesai@gmail.com",             role:"RM",       dept:"Academic",                 designation:"Team Lead",                             location:"Bangalore", password:"Deepa@123"       },
  { empId:"C-1143",   name:"Seema",                            email:"seemac1143@rts.com",                 role:"Requestor", dept:"Marketing",                designation:"Sales Executive",                       location:"Bangalore", password:"Seema@123"       },
  { empId:"G-1003",   name:"Ketan Salamon Nadar",              email:"ketansnadar@gmail.com",              role:"Requestor", dept:"Software",                 designation:"Software Architect",                    location:"Bangalore", password:"Ketan@123"       },
  { empId:"G-1007",   name:"Akhilesh B",                       email:"akhilbetta@gmail.com",               role:"HOD",      dept:"Management",               designation:"Director",                              location:"Bangalore", password:"Akhilesh@123"    },
  { empId:"G-1015",   name:"Sasi Kala Krishnan",               email:"krishnanpr2015@gmail.com",           role:"Requestor", dept:"Accounts",                 designation:"Sr Accountant",                         location:"Bangalore", password:"Sasi@123"        },
  { empId:"G-1020",   name:"Raghuram Kumar",                   email:"raghuramk6@gmail.com",               role:"Requestor", dept:"Corporate Communications", designation:"Software Developer",                    location:"Bangalore", password:"Raghuram@123"    },
  { empId:"G-1033",   name:"Ramya M",                          email:"ramyam@rts.com",                     role:"Requestor", dept:"Software",                 designation:"Software Developer",                    location:"Bangalore", password:"Ramya@123"       },
  { empId:"G-1091",   name:"LALITESHWAR KUMAR",                email:"laliteshwarkumar11@gmail.com",       role:"HOD",      dept:"Software",                 designation:"Software Developer",                    location:"Bangalore", password:"Laliteshwar@123" },
  { empId:"G-1104",   name:"Santosh Kumar",                    email:"mbox.santosh@gmail.com",             role:"HOD",      dept:"Software",                 designation:"Software Architect",                    location:"Bangalore", password:"Santosh@123"     },
  { empId:"G-1117",   name:"Anil Kumar S",                     email:"anilkumarsmart3591@gmail.com",       role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Anil@123"        },
  { empId:"G-1123",   name:"CHETHAN O",                        email:"ramyachethu7@gmail.com",             role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Chethan@123"     },
  { empId:"G-1127",   name:"Abhishek Suresh Hegde",            email:"abhihegde2200@gmail.com",            role:"Requestor", dept:"System admin",             designation:"System Administrator",                  location:"Bangalore", password:"Abhishek@123"    },
  { empId:"G-1136",   name:"Kishor Kumar Baishya",             email:"kishorkumargu@gmail.com",            role:"RM",       dept:"Store",                    designation:"Stores Cum MIS Executive",              location:"Guwahati",  password:"Kishor@123"      },
  { empId:"G-1147",   name:"Ramesh Polipogu",                  email:"ramesh4069@gmail.com",               role:"Requestor", dept:"Broadcasting",             designation:"Network engineer",                      location:"Bangalore", password:"Ramesh@123"      },
  { empId:"G-1148",   name:"Veerabasayya Kulkarni",            email:"veerusk1989@gmail.com",              role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Veerabasayya@123"},
  { empId:"G-1149",   name:"Naveen S Patil",                   email:"nittur.naveen.s@gmail.com",          role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Naveen@123"      },
  { empId:"G-1155",   name:"Nipam Jyoti Kashyap",              email:"nipamjkashyap@gmail.com",            role:"Requestor", dept:"Broadcasting",             designation:"Engineer",                              location:"Guwahati",  password:"Nipam@123"       },
  { empId:"G-1168",   name:"Nakkina Chandra Kiran Kumar",      email:"chandunakkina@gmail.com",            role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Bangalore", password:"Nakkina@123"     },
  { empId:"GC-1202",  name:"Bhagyalakshmi C K",                email:"bhagyaaisha93@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Coordinator",                           location:"Bangalore", password:"Bhagyalakshmi@123"},
  { empId:"GC-1230",  name:"Pritam Sarma",                     email:"pritamsarma500@gmail.com",           role:"RM",       dept:"Operation",                designation:"Team Lead",                             location:"Guwahati",  password:"Pritam@123"      },
  { empId:"GC-1259",  name:"Kishan Shetty",                    email:"kishan.shetty.278@gmail.com",        role:"Requestor", dept:"System admin",             designation:"System Administrator",                  location:"Bangalore", password:"Kishan@123"      },
  { empId:"GC-1298",  name:"Prince Kumar Tiwari",              email:"tiwariprince885@gmail.com",          role:"Requestor", dept:"Operation",                designation:"Technical Executive",                   location:"Maharastra",password:"Prince@123"      },
  { empId:"GC-1299",  name:"Vikas V",                          email:"vikasv.9147@gmail.com",              role:"Requestor", dept:"Accounts",                 designation:"Senior Accountant-Cost",                location:"Bangalore", password:"Vikas@123"       },
  { empId:"GC-1301",  name:"Sourav Deb",                       email:"debs42970@gmail.com",                role:"Requestor", dept:"Store",                    designation:"Store executive",                       location:"Agartala",  password:"Sourav@123"      },
  { empId:"GC-1302",  name:"Tanmoy Deb",                       email:"deb.tanmoy.ece@gmail.com",           role:"Requestor", dept:"Operation",                designation:"Technical Support Executive",           location:"Agartala",  password:"Tanmoy@123"      },
  { empId:"GC-1303",  name:"Tanmoy Deb",                       email:"tanmoydb7@gmail.com",                role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Agartala",  password:"Tanmoy@123"      },
  { empId:"GC-1304",  name:"Joseph Ricky Marcher",             email:"rickma.6568@gmail.com",              role:"RM",       dept:"Operation",                designation:"Project Manager",                       location:"Agartala",  password:"Joseph@123"      },
  { empId:"GC-1306",  name:"Varun M J",                        email:"varunmj131@gmail.com",               role:"Requestor", dept:"Purchase",                 designation:"Purchase Executive",                    location:"Bangalore", password:"Varun@123"       },
  { empId:"GC-1307",  name:"DIVAKAR KUMAR",                    email:"divakarkumar889@gmail.com",          role:"Requestor", dept:"Operation",                designation:"Technical Executive",                   location:"Bhagalpur", password:"Divakar@123"     },
  { empId:"GC-1309",  name:"Palash Choudhury",                 email:"plshchoudhury@gmail.com",            role:"Requestor", dept:"Operation",                designation:"Technical Support Executive",           location:"Agartala",  password:"Palash@123"      },
  { empId:"GC-1310",  name:"Pranab Das",                       email:"daspranab227@gmail.com",             role:"Requestor", dept:"Operation",                designation:"Technical Support Executive",           location:"Agartala",  password:"Pranab@123"      },
  { empId:"GC-1311",  name:"Swagata Lodh",                     email:"lodhsunai19@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Agartala",  password:"Swagata@123"     },
  { empId:"GC-1312",  name:"Ananya Singha",                    email:"ananyasingha2257@gmail.com",         role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Biology",       location:"Agartala",  password:"Ananya@123"      },
  { empId:"GC-1313",  name:"Rajesh Bhowmik",                   email:"rajeshbhowmik418@gmail.com",         role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Agartala",  password:"Rajesh@123"      },
  { empId:"GC-1314",  name:"Kuldip Mallik",                    email:"kuldipmallik4@gmail.com",            role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Agartala",  password:"Kuldip@123"      },
  { empId:"GC-1315",  name:"Dhruba Jyoti Talukdar",            email:"deejey25201@gmail.com",              role:"Requestor", dept:"Store",                    designation:"Store executive",                       location:"Kokrajhar", password:"Dhruba@123"      },
  { empId:"GC-1316",  name:"Rahul Roy",                        email:"ashroy698@gmail.com",                role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - Mathematics",   location:"Agartala",  password:"Rahul@123"       },
  { empId:"GC-1317",  name:"Sangita Kalai",                    email:"kalaisangita29@gmail.com",           role:"Requestor", dept:"Academic",                 designation:"Subject Matter Expert - English",       location:"Agartala",  password:"Sangita@123"     },
  { empId:"GN-1001",  name:"Carol Preethi D'Souza",            email:"preethicarol@gmail.com",             role:"RM",       dept:"Corporate Communications", designation:"Head - Corporate Communications",       location:"Bangalore", password:"Carol@123"       },
  { empId:"GN-1004",  name:"Chandrika R",                      email:"chandrika.acharya@gmail.com",        role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Chandrika@123"   },
  { empId:"GN-1009",  name:"Manjunatha",                       email:"manjumsw75@gmail.com",               role:"HOD",      dept:"Operation",                designation:"Project Manager",                       location:"Bangalore", password:"Manjunatha@123"  },
  { empId:"GN-1010",  name:"Prakash Prabhakar Kulkarni",       email:"edutelprakash@gmail.com",            role:"RM",       dept:"Academic",                 designation:"Team Lead",                             location:"Bangalore", password:"Prakash@123"     },
  { empId:"GN-1011",  name:"Pruthvi Raj R",                    email:"pruthvi2k7@gmail.com",               role:"HOD",      dept:"Animation",                designation:"Team Lead",                             location:"Bangalore", password:"Pruthvi@123"     },
  { empId:"GN-1012",  name:"PUNDARIKA PERLAMPADY",             email:"pundarikagowda.p@gmail.com",         role:"RM",       dept:"Store",                    designation:"Senior Executive",                      location:"Bangalore", password:"Pundarika@123"   },
  { empId:"GN-1015",  name:"SRIDHAR M N",                      email:"sridharmn99@gmail.com",              role:"RM",       dept:"Academic",                 designation:"HOD - Biology",                         location:"Bangalore", password:"Sridhar@123"     },
  { empId:"GN-1016",  name:"Sudhakara B G",                    email:"sudhakarmdr@gmail.com",              role:"Requestor", dept:"Govt. Relations",          designation:"Project Manager",                       location:"Bangalore", password:"Sudhakara@123"   },
  { empId:"GN-1018",  name:"Vikas Deep",                       email:"vikasdeep@gumbisoftware.com",        role:"HOD",      dept:"Business Development",     designation:"Vice President",                        location:"Bangalore", password:"Vikas@123"       },
  { empId:"GN-1020",  name:"GANESH M KHARVI",                  email:"gmkharvik@gmail.com",                role:"Requestor", dept:"Animation",                designation:"Sr. 2D Animator",                       location:"Bangalore", password:"Ganesh@123"      },
  { empId:"GN-1023",  name:"Vinaya Keshava Y",                 email:"vinayakeshava@gmail.com",            role:"HOD",      dept:"System admin",             designation:"Studio manager/IT manager",             location:"Bangalore", password:"Vinaya@123"      },
  { empId:"GN-1033",  name:"Sharath H",                        email:"sharath.rockz90@gmail.com",          role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Sharath@123"     },
  { empId:"GN-1035",  name:"Mylesh G",                         email:"myleshprince@gmail.com",             role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Mylesh@123"      },
  { empId:"GN-1041",  name:"Parameshwar V Hegde",              email:"vivekhegde09@gmail.com",             role:"Requestor", dept:"Accounts",                 designation:"Assistant Finance Manager",             location:"Bangalore", password:"Parameshwar@123" },
  { empId:"GN-1042",  name:"Sudhakar G Hegde",                 email:"sghegde2010@gmail.com",              role:"HOD",      dept:"HR",                       designation:"Team Lead",                             location:"Bangalore", password:"Sudhakar@123"    },
  { empId:"GN-1046",  name:"Anjanjyoti Deka",                  email:"deka.anjanj@gmail.com",              role:"Requestor", dept:"Academic",                 designation:"Manager L&D - Academic",                location:"Guwahati",  password:"Anjanjyoti@123"  },
  { empId:"GN-1049",  name:"Rabiul Hoque Chawdhury",           email:"rubulchawdhury343@gmail.com",        role:"Requestor", dept:"Academic",                 designation:"Sr.Subject Matter Expert - Mathematics",location:"Guwahati",  password:"Rabiul@123"      },
  { empId:"GN-1051",  name:"Manjunath Bhat K R",               email:"manjuhavyaka@gmail.com",             role:"Requestor", dept:"Broadcasting",             designation:"Studio Engineer",                       location:"Bangalore", password:"Manjunath@123"   },
  { empId:"GN-1054",  name:"PRAJALITA SHARMA",                 email:"pra.rubys@gmail.com",                role:"Requestor", dept:"Academic",                 designation:"Sr.Subject Matter Expert - English",    location:"Guwahati",  password:"Prajalita@123"   },
  { empId:"GN-1062",  name:"Veeresh Shivayogi Manvi",          email:"veereshmanvi9@gmail.com",            role:"Requestor", dept:"Animation",                designation:"3D Generalist",                         location:"Hubli",     password:"Veeresh@123"     },
  { empId:"GN-1063",  name:"Santhosh K M",                     email:"santhukm038@gmail.com",              role:"Requestor", dept:"Animation",                designation:"3D Artist",                             location:"Bangalore", password:"Santhosh@123"    },
  { empId:"GN-1066",  name:"Sachin G",                         email:"sachinsgr564@gmail.com",             role:"Requestor", dept:"Animation",                designation:"3D Animator",                           location:"Bangalore", password:"Sachin@123"      },
  { empId:"GN-1068",  name:"Shivaram S T",                     email:"sshivaram937@gmail.com",             role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Shivaram@123"    },
  { empId:"GN-1069",  name:"Prasanna Ramling Police Patil",    email:"prasannapolicepatil7@gmail.com",     role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Prasanna@123"    },
  { empId:"GN-1300",  name:"Jagadeesh S K",                    email:"skjagadeeshmy@gmail.com",            role:"Requestor", dept:"Animation",                designation:"2D Animator",                           location:"Bangalore", password:"Jagadeesh@123"   },
  { empId:"UC-1003",  name:"Bhaigyashree Daimari",             email:"bhaigyadaimari@gmail.com",           role:"Requestor", dept:"HR",                       designation:"EXECUTIVE-HR",                          location:"Guwahati",  password:"Bhaigyashree@123"},

  // ── DEPARTMENT HODs — login: dept@rts.com / Dept@123 ─────────────────────
  { empId:"DHOD-ACADE", name:"Academic Department HOD",                email:"academic@rts.com",                role:"DeptHOD", dept:"Academic",                 designation:"Department Head", location:"HQ", password:"Academic@123"                },
  { empId:"DHOD-ACCOU", name:"Accounts Department HOD",                email:"accounts@rts.com",                role:"DeptHOD", dept:"Accounts",                 designation:"Department Head", location:"HQ", password:"Accounts@123"                },
  { empId:"DHOD-ADMIN", name:"Admin Department HOD",                   email:"admin.dept@rts.com",              role:"DeptHOD", dept:"Admin",                    designation:"Department Head", location:"HQ", password:"Admin@123"                   },
  { empId:"DHOD-ANIMA", name:"Animation Department HOD",               email:"animation@rts.com",               role:"DeptHOD", dept:"Animation",                designation:"Department Head", location:"HQ", password:"Animation@123"               },
  { empId:"DHOD-BROAD", name:"Broadcasting Department HOD",            email:"broadcasting@rts.com",            role:"DeptHOD", dept:"Broadcasting",             designation:"Department Head", location:"HQ", password:"Broadcasting@123"            },
  { empId:"DHOD-BUSIN", name:"Business Development Department HOD",    email:"businessdevelopment@rts.com",     role:"DeptHOD", dept:"Business Development",     designation:"Department Head", location:"HQ", password:"Businessdevelopment@123"     },
  { empId:"DHOD-CORPO", name:"Corporate Communications Department HOD",email:"corporatecommunications@rts.com", role:"DeptHOD", dept:"Corporate Communications", designation:"Department Head", location:"HQ", password:"Corporatecommunications@123"  },
  { empId:"DHOD-DOCUM", name:"Documantation Department HOD",           email:"documantation@rts.com",           role:"DeptHOD", dept:"Documantation",            designation:"Department Head", location:"HQ", password:"Documantation@123"           },
  { empId:"DHOD-GOVTR", name:"Govt. Relations Department HOD",         email:"govtrelations@rts.com",           role:"DeptHOD", dept:"Govt. Relations",          designation:"Department Head", location:"HQ", password:"Govtrelations@123"           },
  { empId:"DHOD-HR",    name:"HR Department HOD",                      email:"hr@rts.com",                      role:"DeptHOD", dept:"HR",                       designation:"Department Head", location:"HQ", password:"Hr@123"                      },
  { empId:"DHOD-MANAG", name:"Management Department HOD",              email:"management@rts.com",              role:"DeptHOD", dept:"Management",               designation:"Department Head", location:"HQ", password:"Management@123"              },
  { empId:"DHOD-MARKE", name:"Marketing Department HOD",               email:"marketing@rts.com",               role:"DeptHOD", dept:"Marketing",                designation:"Department Head", location:"HQ", password:"Marketing@123"               },
  { empId:"DHOD-OPERA", name:"Operation Department HOD",               email:"operation@rts.com",               role:"DeptHOD", dept:"Operation",                designation:"Department Head", location:"HQ", password:"Operation@123"               },
  { empId:"DHOD-PURCH", name:"Purchase Department HOD",                email:"purchase@rts.com",                role:"DeptHOD", dept:"Purchase",                 designation:"Department Head", location:"HQ", password:"Purchase@123"                },
  { empId:"DHOD-SOFTW", name:"Software Department HOD",                email:"software@rts.com",                role:"DeptHOD", dept:"Software",                 designation:"Department Head", location:"HQ", password:"Software@123"                },
  { empId:"DHOD-STORE", name:"Store Department HOD",                   email:"store@rts.com",                   role:"DeptHOD", dept:"Store",                    designation:"Department Head", location:"HQ", password:"Store@123"                   },
  { empId:"DHOD-SYSTE", name:"System admin Department HOD",            email:"systemadmin@rts.com",             role:"DeptHOD", dept:"System admin",             designation:"Department Head", location:"HQ", password:"Systemadmin@123"             },
  { empId:"DHOD-TECHN", name:"Technical Support Department HOD",       email:"technicalsupport@rts.com",        role:"DeptHOD", dept:"Technical Support",        designation:"Department Head", location:"HQ", password:"Technicalsupport@123"        },

  // ── SYSTEM ADMIN ──────────────────────────────────────────────────────────
  { empId:"ADMIN-001", name:"System Admin", email:"admin@rts.com", role:"Admin", dept:"Management", designation:"System Administrator", location:"HQ", password:"Admin@123" },
];

async function main() {
  console.log(`\n📦  RTS Seeder — ${USERS.length} users to process\n`);
  let created = 0, skipped = 0;

  for (const u of USERS) {
    const emailLower = u.email.toLowerCase();
    const hash = await bcrypt.hash(u.password, 10);

    // Skip if already seeded (safe to re-run)
    const exists = await prisma.user.findFirst({
      where: {
        OR: [
          { empId: u.empId },
          { email: emailLower }
        ]
      }
    });

    if (exists) {
      // If user exists, we UPDATE it to ensure password matches the seed
      await prisma.user.update({
        where: { id: exists.id },
        data: {
          passwordHash: hash,
          role:         u.role, // ensure role is correct too
          dept:         u.dept,
        }
      });
      process.stdout.write(`   ↩  ${u.empId.padEnd(14)} updated (password reset)\n`);
      skipped++;
      continue;
    }

    await prisma.user.create({
      data: {
        empId:        u.empId,
        name:         u.name,
        email:        emailLower,
        passwordHash: hash,
        role:         u.role,
        dept:         u.dept,
        designation:  u.designation || null,
        location:     u.location   || null,
      },
    });
    console.log(`   ✔  ${u.role.padEnd(8)} ${u.empId.padEnd(14)} ${u.name.padEnd(38)} ${u.email}`);
    created++;
  }

  console.log(`\n✅  Done: ${created} created, ${skipped} skipped.\n`);
  console.log("🔑  Login reference:");
  console.log("   Employees/RM/HOD → Gmail from Excel  | FirstName@123");
  console.log("   DeptHODs         → dept@rts.com      | Dept@123");
  console.log("                      software@rts.com  | Software@123");
  console.log("   Admin            → admin@rts.com     | Admin@123\n");
}

main()
  .catch((e) => { console.error("❌  Seed failed:", e); process.exit(1); })
  .finally(() => prisma.$disconnect());
